# curl -X POST http://localhost:3000/user/f825c498-f40b-4958-acb9-1aef590c33a0
# -H 'Content-Type: application/json'
# -d '"name": "Javier"'

curl -X POST http://localhost:3000/user/f825c498-f40b-4958-acb9-1aef590c33a0 -H 'Content-Type: application/json' -d {"name": "Javier"}
